spring:
  application:
    name: ${springboot.app.name:zuul}

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://discovery:8761/eureka/}

zuul:
  ignored-services: "*"
  routes:
    hello-web:
      path: /
      serviceId: hello-web
